# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install landscapes
        run: python setup.py install
          
      - name: Run tests
        run: python -m unittest tests/test_single_objective.py
        
      - name: Submit to codecov
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          pip install coverage
          coverage run -m unittest tests/test_single_objective.py 
          bash <(curl -s https://codecov.io/bash)
